### ISSUE TITLE
Start up crash: Possible conflict with Ice and Fire and Thaumic Additions +/- Hammercore

### ISSUE THREAD

**Issue by DWX12** [Zeitheron/ThaumicAdditions#3]
## I have read the following rules:
1. Ensure that you are running the latest HammerCore, Thaumcraft, Baubles and Thaumic Additions
2. If you have a video about the issue, upload it to YouTube and leave a link at Attachments section
3. Try to avoid walls of text in description.
4. You should provide a way how to reproduce the issue you are experiencing. (If possible)
5. You should use the template provided below; Do not remove the agreement  (below), as the issue is just going to be closed and most likely not fixed.
###### I agree that if any rule is ignored then this issue may be closed without fixing it.

# Description:
Describe the issue you are having...
Start up crash when adding Thaumic Additions along side Ice and Fire.
Draco aspect conflict:

Caused by: java.lang.IllegalArgumentException: draco already registered!
	at thaumcraft.api.aspects.Aspect.<init>(Aspect.java:39)
	at com.github.alexthe666.iceandfire.IceAndFireAspectRegistry.<clinit>(IceAndFireAspectRegistry.java:17)

I have a large modpack; crashes upon adding Thaumic Additions + Hammercore. Starts up fine otherwise.

# How to reproduce (step by step):
1. Start up Minecraft
2. Receive Crash Report
3. Profit

# Versions:
##### Thaumic Additions Version: xx

# Attachments:
(Crash reports or screenshots)

https://hastebin.com/felexojana.bash

# Mod List:
* HammerCore (1.9.9.7)
* ThaumicAdditions (2r)
* Thaumcraft (Beta 14)
* Baubles (1.5.2)
*Ice and FIre
* Other...

Full mod list available in crash report.

**Comment by Zeitheron** [comment]
Either remove any of conflicting mods ("Thaumic Additions" or "Ice and Fire") or ask them to rename the aspect. I am not going to rename my aspect.

**Comment by drakray** [comment]
just a quick question about that: for modder adding new aspect, shouldn't they always test for existing name, if exist, skip register, if not, register aspect? I know that can make their mod use an aspect that is not composed of subaspect they want, but at least the "already registered" crash woulnd't happen, I think.

**Comment by Zeitheron** [comment]
Yes, they could also make use already registered aspect, that's also possible
